### ISSUE TITLE
Mock routing support

### ISSUE THREAD

**Issue by DaBrown95** [hunterlester/safe-app-base#2]
I am using this with the latest SAFE Browser, v0.8.0 with mock support. The app never receives an 'auth-response' from the SAFE Browser after you authenticate in the browser. Is this an issue with this app or does it just not support mock routing? Any help you can give would be greatly appreciated.

**Comment by hunterlester** [comment]
I'm thinking that you are using Windows.

In your SAFE Browser folder that you unzipped, look for `SAFE Browser.exe` and `SAFE Browser.crust.config`. 
Rename them to `safe-browser.exe` and `safe-browser.crust.config`, respectively.

Also, just in case you also have white space in your path elsewhere:
Prior to renaming those files, open up your `Registry Editor` program and navigate to `Computer\HKEY_CLASSES_ROOT\safe-auth\shell\open\command`

Will you please copy and paste the command that you see here?

Thank you for reporting this.

I'm thinking that is is a white space issue that we need to handle.

**Comment by hunterlester** [comment]
It's been a while since I've run this example. I'll see if I can get it to throw an error.

**Comment by DaBrown95** [comment]
Not using Windows, running the very latest macOS. Interested in working with you to help test/update this example if required!

**Comment by DaBrown95** [comment]
Just to clarify my process, I am running the very latest version of macOS.
I use `export NODE_ENV=dev`, followed by the rest of the commands you recommend. What tipped me off that something isn't working, is that `console.log(mdata);` never gets triggered. So I tested this by placing another simple `console.log("Hello World")` within the listener but it never prints to the console. Hence leading to my suspicion that there is something not quite right... I have looked through Maidsafe's other examples but sadly have not found anything.

**Comment by hunterlester** [comment]
I just pushed an update to this repo. Pull the latest and see how it works for you.
Let me know about any further issues.

The issue was simply that `safe_app_nodejs` now installs itself as `@maidsafe/safe-node-app` in `node_modules` and my code was still requiring it as `safe-app`.

**Comment by DaBrown95** [comment]
That does make sense. Upon building it through 'yarn package' I am faced with this error.
<img width="456" alt="screen shot 2017-12-06 at 17 12 22" src="https://user-images.githubusercontent.com/11600230/33674841-a5df4d02-daa8-11e7-9b85-2f06ff0929bc.png">
Deleted the node_modules folder but still faced with this. Odd that it doesn't do this when ran through `yarn start`

**Comment by hunterlester** [comment]
Did you previously have a `yarn.lock` present?
Delete that and run `yarn` once more.
I don't understand how it works completely, but Electron pulls it's resources from `yarn.lock`.

**Comment by DaBrown95** [comment]
Didn't think about that one, well suggested! Removed it but sadly the same outcome... I wonder if Electron packager just doens't like the naming of the safe module.

**Comment by hunterlester** [comment]
hmmmm...
I just deleted my directory and cloned this repo from scratch, with success.
I'm wondering if what's happening is a problem with how `yarn` works.

In the rendered view, see how it says you are using Node.js `7.9.0`?
I'll bet that's different than what you have installed on your system. Which version are you using?

When opening up `yarn.lock` what is the information that you see about the `@maidafe/safe-node-app` dependency?

Trying deleting your `yarn.lock` and only using `npm` commands.

**Comment by DaBrown95** [comment]
Yarn can be a little confusing sometimes with the way it works haha...
I am just using a recent version of Node 8, 8.9.0 I think. So for fun, I tried it with Node 7.9.0 and used the npm commands and it works! It doesn't throw that error now. 

For the maidsafe app dependency I am seeing this...

> "@maidsafe/safe-node-app@0.5.2":
  version "0.5.2"
  resolved "https://registry.yarnpkg.com/@maidsafe/safe-node-app/-/safe-node-app-0.5.2.tgz#9f88116d248e08df6ffb0ccd200b2849168587b5"
  dependencies:
    deps_downloader "https://s3.eu-west-2.amazonaws.com/deps-downloader/deps_downloader-0.1.0.tgz"
    enum "^2.3.0"
    ffi "^2.2.0"
    ref "^1.3.3"
    ref-array "^1.2.0"
    ref-struct "^1.1.0"
    weak "^1.0.1"

**Comment by DaBrown95** [comment]
Can confirm also that when I use Node version 7.9.0 that yarn is working too. Although there is still no output to the dev console in the app for `console.log(mdata);`.

Thank you for all your help on this btw 😄

**Comment by hunterlester** [comment]
When you start the app, is SAFE Browser prompting you for authorisation?

**Comment by DaBrown95** [comment]
Yeah the browser does, ask, if for example I put `console.log("Hello")` within `listenForAuthReponse` that never gets printed. Which from my understanding should do after I authenticate within the browser.

**Comment by hunterlester** [comment]
On Windows, applications are registered and can be viewed via `Registry Editor`. Where does that occur on OSX?
I'd like to take a look at the ID and command that's registered for the `safe-app-base` app.

**Comment by DaBrown95** [comment]
Starting to think this is just a small Mac quirk. So I tested it on Windows and it works as expected. On macOS the equivalent is somewhere within `~Library/Preferences`. What I notice is the Maidsafe's own apps have info in there but for some reason, this app doesn't. My first guess was to properly set the `electronPackager` config options but that doesn't appear to work. What I can't figure out is what is the difference between this app and the official Maidsafe apps. Do you have any ideas? Because otherwise I guess this example will need to be marked as Windows/Linux only until me/you/someone else can figure out why.

Should we bring attention to this in the forums to see if anyone else has encountered this before?
